services:
  backend:
    build: ./backend # Build from your backend/Dockerfile
    container_name: backend # Name of the container
    ports:
      - "8000:8000" # Expose FastAPI on localhost:8000
    depends_on:
      - mongo # Ensure Mongo starts before backend
      - goquorum # Ensure GoQuorum starts before backend
    environment: # Environment variables for backend
      - MONGO_URI=mongodb://mongo:27017/ # Use service name "mongo", not localhost
      - DB_NAME=cert_verification # Database name (auto-created on first use)
      - BLOCKCHAIN_NODE=http://goquorum:8545 # Quorum node endpoint (inside Docker network)
      - CONTRACT_ADDRESS=0xB08D36320fe0af713081ce8D0085Ecc6f6e74664 # Set to deployed CertRegistry address (e.g., 0xabc...)
      - SECRET_KEY=your-super-secret-key-change-in-production-please # JWT secret key
      - ADMIN_USERNAME=admin # Default admin username
      - ADMIN_EMAIL=admin@certificate-system.com # Default admin email
      - ADMIN_PASSWORD=admin123456 # Default admin password (CHANGE THIS!)
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    # The command runs your FastAPI app inside the backend container.

  mongo:
    image: mongo:6.0 # Official MongoDB image
    container_name: mongo # Name of the Mongo container
    ports:
      - "27017:27017" # Expose Mongo on localhost:27017
    volumes:
      - mongo_data:/data/db # Persist database data in a named volume

  goquorum:
    image: trufflesuite/ganache-cli:latest # Using Ganache CLI as a simpler Ethereum alternative
    container_name: goquorum-node # Name of the Ethereum node container
    ports:
      - "8545:8545" # JSON-RPC endpoint (used by Web3.py)
    command: >
      --host 0.0.0.0
      --port 8545
      --networkId 1337
      --accounts 10
      --deterministic
      --mnemonic "your development mnemonic here for testing only"

volumes:
  mongo_data: # Named volume for MongoDB persistence
